apiVersion: v1
kind: ConfigMap
metadata:
  name: diun-config
  namespace: homelab
data:
  TZ: "Asia/Manila"
  DIUN_WATCH_WORKERS: "20"
  DIUN_WATCH_SCHEDULE: "0 */6 * * *"
  DIUN_WATCH_JITTER: "30s"
  DIUN_PROVIDERS_DOCKER: "true"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: diun-data
  namespace: homelab
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: diun
  namespace: homelab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: diun
  template:
    metadata:
      labels:
        app: diun
    spec:
      containers:
      - name: diun
        image: crazymax/diun:latest
        command: ["diun", "serve"]
        envFrom:
        - configMapRef:
            name: diun-config
        volumeMounts:
        - name: data
          mountPath: /data
        - name: docker-sock
          mountPath: /var/run/docker.sock
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: diun-data
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
          type: Socket
      restartPolicy: Always
