apiVersion: v1
kind: Secret
metadata:
  name: mssql-secret
  namespace: homelab
type: Opaque
stringData:
  MSSQL_SA_PASSWORD: "<secret>"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mssql-config
  namespace: homelab
data:
  ACCEPT_EULA: "Y"
  TZ: "Asia/Manila"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-data
  namespace: homelab
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-log
  namespace: homelab
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-secrets
  namespace: homelab
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql
  namespace: homelab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mssql
  template:
    metadata:
      labels:
        app: mssql
    spec:
      containers:
      - name: server
        image: mcr.microsoft.com/mssql/server:2022-latest
        securityContext:
          capabilities:
            add:
            - SYS_PTRACE
        envFrom:
        - configMapRef:
            name: mssql-config
        - secretRef:
            name: mssql-secret
        ports:
        - containerPort: 1433
        volumeMounts:
        - name: data
          mountPath: /var/opt/mssql/data
        - name: log
          mountPath: /var/opt/mssql/log
        - name: secrets
          mountPath: /var/opt/mssql/secrets
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: mssql-data
      - name: log
        persistentVolumeClaim:
          claimName: mssql-log
      - name: secrets
        persistentVolumeClaim:
          claimName: mssql-secrets
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: mssql
  namespace: homelab
spec:
  type: NodePort
  selector:
    app: mssql
  ports:
  - name: sql
    port: 1433
    targetPort: 1433
    nodePort: 31433
