apiVersion: v1
kind: ConfigMap
metadata:
  name: oraclesql-config
  namespace: homelab
data:
  ORACLE_CHARACTERSET: "AL32UTF8"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oraclesql-oradata
  namespace: homelab
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oraclesql-backup
  namespace: homelab
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oraclesql
  namespace: homelab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oraclesql
  template:
    metadata:
      labels:
        app: oraclesql
    spec:
      containers:
      - name: express
        image: container-registry.oracle.com/database/express:21.3.0-xe
        envFrom:
        - configMapRef:
            name: oraclesql-config
        ports:
        - containerPort: 1521
        - containerPort: 5500
        volumeMounts:
        - name: oradata
          mountPath: /opt/oracle/oradata
        - name: backup
          mountPath: /opt/oracle/backup
      volumes:
      - name: oradata
        persistentVolumeClaim:
          claimName: oraclesql-oradata
      - name: backup
        persistentVolumeClaim:
          claimName: oraclesql-backup
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: oraclesql
  namespace: homelab
spec:
  type: NodePort
  selector:
    app: oraclesql
  ports:
  - name: sql
    port: 1521
    targetPort: 1521
    nodePort: 31521
  - name: em
    port: 5500
    targetPort: 5500
    nodePort: 30550
